// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLraWCUxKZXj-0EJCM0lmaK6laYQ99ewA',
    appId: '1:121502446229:web:434dddc7f49e59c527e19c',
    messagingSenderId: '121502446229',
    projectId: 'court-snapp',
    authDomain: 'court-snapp.firebaseapp.com',
    storageBucket: 'court-snapp.firebasestorage.app',
    measurementId: 'G-YSY2CPS9QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMxy_Qk1P34TDIwOihW0blaHBDXwPU7tk',
    appId: '1:121502446229:android:e7629c1258a57b8c27e19c',
    messagingSenderId: '121502446229',
    projectId: 'court-snapp',
    storageBucket: 'court-snapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV8WkpNCQQv8EjGLPIVl_O9k9QPSaW4R0',
    appId: '1:121502446229:ios:e95bd266df3a4bcf27e19c',
    messagingSenderId: '121502446229',
    projectId: 'court-snapp',
    storageBucket: 'court-snapp.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
